workflows:
  full-release:
    name: Build & Deploy (iOS + Android)
    max_build_duration: 60

    environment:
      groups:
        - release-keystore-group  # يحتوي على المتغيرات التالية:
                                  # CM_KEYSTORE
                                  # CM_KEYSTORE_PASSWORD
                                  # CM_KEY_ALIAS
                                  # CM_KEY_PASSWORD

      vars:
        XCODE_PROJECT: "SkillJoy.xcodeproj"
        XCODE_SCHEME: "SkillJoy"
        BUNDLE_ID: "org.reactjs.native.example.SkillJoy"
        CM_KEYSTORE_PATH: android/app/my-release-key.keystore  # ✅ أضف هذا السطر هنا

      node: latest
      xcode: latest
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd android
          chmod +x ./gradlew
          ./gradlew dependencies
          cd ../ios
          pod install
          cd ..

      - name: Decode keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/my-release-key.keystore

      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease -PKEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD -PKEY_ALIAS=$CM_KEY_ALIAS -PKEY_PASSWORD=$CM_KEY_PASSWORD

      - name: Build iOS
        script: |
          xcodebuild \
            -project ios/${XCODE_PROJECT} \
            -scheme ${XCODE_SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            archive -archivePath $CM_BUILD_DIR/SkillJoy.xcarchive

      - name: Export iOS .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/SkillJoy.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ios

    artifacts:
      - android/app/build/outputs/**/*.apk
      - build/ios/*.ipa

    # يمكنك تفعيل النشر لاحقًا عند الحاجة:
    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    #     key_id: $APP_STORE_CONNECT_KEY_ID
    #     issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    #     submit_to_testflight: true

    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal
